[build]
  command = "npm ci && npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION   = "20"
  NETLIFY        = "true"
  NODE_OPTIONS   = "--max-old-space-size=4096"
  NPM_FLAGS      = "--prefer-offline"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
